---

- name: Installing dependencies
  apt:
    name:
      - python
      - python-dev
      - git
      - python-pip
      - python3-pip
      - python-setuptools
      - kvm
      - fping
      - curl
      - libffi-dev
      - gcc
      - libssl-dev
      - python-selinux
    state: present
  when:
    - (inventory_hostname == openvpn_node and not action_type) or inventory_hostname in other_nodes

- name: Installing docker
  shell: which docker || (curl -sSL https://get.docker.com/ | sh)
  when:
    - (inventory_hostname == openvpn_node and not action_type) or inventory_hostname in other_nodes

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /tmp/docker/volumes
    - /var/lib/docker/volumes
    - /tmp/nova
    - /var/lib/nova
  when:
    - g5k
    - (inventory_hostname == openvpn_node and not action_type) or inventory_hostname in other_nodes

- name: Bind volumes of docker in /tmp (free storage location on G5k)
  command: mount --bind /tmp/docker/volumes /var/lib/docker/volumes
  when:
    - g5k
    - (inventory_hostname == openvpn_node and not action_type) or inventory_hostname in other_nodes

- name: Bind nova local storage in /tmp
  command: mount --bind /tmp/nova /var/lib/nova
  when:
    - g5k
    - (inventory_hostname == openvpn_node and not action_type) or inventory_hostname in other_nodes

- name: Piping
  pip:
    name: "{{ item }}"
  loop:
    - ansible
    - kolla-ansible
  when:
    - (inventory_hostname == openvpn_node and not action_type) or inventory_hostname in other_nodes

- name: Generates ssh key if not present
  local_action:
    module: command ssh-keygen -b 4096 -q -t rsa -f '{{ exec_dir }}/current/kolla_ssh' -C '' -N ''
    args:
      creates: '{{ exec_dir }}/current/kolla_ssh'
  run_once: true
  when:
    - inventory_hostname == openvpn_node

- name: Copy the private ssh key to control
  copy:
    src: "{{ exec_dir }}/current/kolla_ssh"
    dest: /root/.ssh/kolla_ssh
    mode: u+rw,g-rwx,o-rwx
  when:
    - inventory_hostname == openvpn_node

- name: Copy the public ssh key to hosts
  copy:
    src: "{{ exec_dir }}/current/kolla_ssh.pub"
    dest: /root/.ssh/kolla_ssh.pub
  when:
    - inventory_hostname == openvpn_node or inventory_hostname in other_nodes

- name: Adding the key to authorized keys
  shell: "cat /root/.ssh/kolla_ssh.pub >> .ssh/authorized_keys"
  when:
    - inventory_hostname == openvpn_node or inventory_hostname in other_nodes

  # WHEN RUNNING FIRST TIME (not adding a node)

- name: Copy ansible config file
  copy:
    src: ansible.cfg
    dest: /root/ansible.cfg
  when:
    - inventory_hostname == openvpn_node

- name: Create local working directory (/srv/init_os)
  file:
    path: /srv/init_os
    state: directory

- name: Download reference images
  shell: "ls -l /srv/init_os/{{ item.name }}.qcow2 || curl -L -o /srv/init_os/{{ item.name }}.qcow2 {{ item.url }}"
  loop: "{{ images }}"

# FROM ENOS
- name: Mount /run
  command: mount --make-shared /run

# Note: nscd prevents kolla-toolbox to start
# See, https://bugs.launchpad.net/kolla-ansible/+bug/1680139
- name: Stop nscd service (prevents kolla-toolbox to start)
  systemd:
    state: stopped
    name: nscd
  ignore_errors: yes

- name: Deploy OpenStack
  include: main_node.yml
  when:
    - inventory_hostname == openvpn_node

- name: Init OpenStack
  include: init_os.yml
  when:
    - inventory_hostname == config['resources']['network'][0]['host']
