# how many nodes for each roles
nodes:
  control: 1
  network: 1
  compute: 2

# which node to put the role onto
# begins at 0 (localhost)
# take the number of roles into account, e.g.
# if control has 3 nodes and begins at 2,
# network has to begin at 5 minimum
all-in-one:
  deploy: 1
  control: 2
  network: 3
  compute: 4

ssh_key: ~/enos_openvpn/current/ansible

network:
  network1: 11.8
  network2: 11.8
  mask: 17

kolla:
  kolla_internal_ip: 11.8.0.254
  network_interface: tap0
  neutron_external_interface: tap1
  os_version: rocky
  os_password: demo

images:
  - name: debian-9
    url: https://cdimage.debian.org/cdimage/openstack/current-9/debian-9-openstack-amd64.qcow2
  - name: cirros.uec
    url: http://download.cirros-cloud.net/0.3.4/cirros-0.3.4-x86_64-disk.img
