---

- name: Installing dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python
    - python-dev
    - git
    - python-pip
    - python3-pip
    - python-setuptools
    - kvm
    - fping
    - curl
    - libffi-dev
    - gcc
    - libssl-dev
    - python-selinux
  when:
    - (inventory_hostname == openvpn_node and not action_type) or inventory_hostname in other_nodes

- name: Installing docker
  shell: which docker || (curl -sSL https://get.docker.com/ | sh)
  when:
    - (inventory_hostname == openvpn_node and not action_type) or inventory_hostname in other_nodes

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /tmp/docker/volumes
    - /var/lib/docker/volumes
    - /tmp/nova
    - /var/lib/nova
  when:
    - g5k
    - (inventory_hostname == openvpn_node and not action_type) or inventory_hostname in other_nodes

- name: Bind volumes of docker in /tmp (free storage location on G5k)
  command: mount --bind /tmp/docker/volumes /var/lib/docker/volumes
  when:
    - g5k
    - (inventory_hostname == openvpn_node and not action_type) or inventory_hostname in other_nodes

- name: Bind nova local storage in /tmp
  command: mount --bind /tmp/nova /var/lib/nova
  when:
    - g5k
    - (inventory_hostname == openvpn_node and not action_type) or inventory_hostname in other_nodes

- name: Piping
  pip:
    name: "{{ item }}"
  loop:
    - ansible
    - kolla-ansible
  when:
    - (inventory_hostname == openvpn_node and not action_type) or inventory_hostname in other_nodes

- name: Deploy OpenStack
  include: not_action.yml
  when:
    - not action_type

- name: Create local working directory (/srv/init_os)
  file:
    path: /srv/init_os
    state: directory

- name: Download reference images
  shell: "ls -l /srv/init_os/{{ item.name }}.qcow2 || curl -L -o /srv/init_os/{{ item.name }}.qcow2 {{ item.url }}"
  loop: "{{ images }}"

# FROM ENOS
- name: Mount /run
  command: mount --make-shared /run

# Note: nscd prevents kolla-toolbox to start
# See, https://bugs.launchpad.net/kolla-ansible/+bug/1680139
- name: Stop nscd service (prevents kolla-toolbox to start)
  systemd:
    state: stopped
    name: nscd
  ignore_errors: yes

- name: Deploy OpenStack
  include: main_node.yml
  when:
    - inventory_hostname == openvpn_node

- name: Init OpenStack
  include: init_os.yml
  when:
    - inventory_hostname == config['resources']['network'][0]['host']
