
- name: Installing docker
  shell: (curl -sSL https://get.docker.com/ | sh)


- name: Installing dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python
    - python-dev
    - git
    - python-pip
    - python3-pip

- name:
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /tmp/docker/volumes
    - /var/lib/docker/volumes
    - /tmp/nova
    - /var/lib/nova
  when: g5k


- name: Bindmounting docker
  mount:
    path: /tmp/docker/volumes
    src: /var/lib/docker/volumes
    opts: bind
    fstype: none
    state: present
  when: g5k


- name: Bindmounting nova
  mount:
    path: /tmp/nova
    src: /var/lib/nova
    opts: bind
    fstype: none
    state: present
  when: g5k


- name: Getting virtualenv
  pip:
    name: virtualenv
  when: inventory_hostname == openvpn_node

# - name: Getting enos
#   pip:
#     name: git+https://github.com/marie-donnie/enos.git@limit#egg=enos
#     editable: true
#     executable: pip3
#   when: inventory_hostname == openvpn_node


- name: Generates ssh key if not present
  local_action:
    module: command ssh-keygen -b 4096 -q -t rsa -f '{{ exec_dir }}/current/ssh' -C '' -N ''
    args:
      creates: '{{ exec_dir }}/current/ssh'
  run_once: true

- name: Copy the private ssh key to control
  copy:
    src: "{{ exec_dir }}/current/ssh"
    dest: /root/.ssh/ssh
    mode: u+rw,g-rwx,o-rwx
  when: inventory_hostname == openvpn_node

- name: Copy the public ssh key to hosts
  copy:
    src: "{{ exec_dir }}/current/ssh.pub"
    dest: /root/.ssh/ssh.pub

- name: Adding the key to authorized keys
  shell: "cat /root/.ssh/ssh.pub >> .ssh/authorized_keys"

- name: Copy ansible config file
  copy:
    src: ansible.cfg
    dest: /root/ansible.cfg
  when: inventory_hostname == openvpn_node

- name: Piping
  shell: "virtualenv venv"
  args:
    creates: "venv/bin/activate"
  when: inventory_hostname == openvpn_node


- name: Adding reservation file
  copy:
    src: "{{ exec_dir }}/reservation.yaml"
    dest: reservation.yaml
  when: inventory_hostname == openvpn_node


- name: Executing enos
  shell: ". venv/bin/activate; enos deploy > /tmp/enos.logs"
  when: inventory_hostname == openvpn_node
