- name: Installing dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python
    - python-dev
    - git
    - python-pip


- name:
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /tmp/docker/volumes
    - /var/lib/docker/volumes
    - /tmp/nova
    - /var/lib/nova
  when: "{{ g5k }}"


- name: Bindmounting docker
  mount:
    path: /tmp/docker/volumes
    src: /var/lib/docker/volumes
    opts: bind
    fstype: none
    state: present
  when: "{{ g5k }}"


- name: Bindmounting docker
  mount:
    path: /tmp/nova
    src: /var/lib/nova
    opts: bind
    fstype: none
    state: present
  when: "{{ g5k }}"


- name: Getting virtualenv
  pip:
    name: virtualenv
  when: inventory_hostname == openvpn_node

- name: Getting enos
  pip:
    name: git+https://github.com/beyondtheclouds/enos.git@stable/queens#egg=enos
    editable: true
  when: inventory_hostname == openvpn_node

- name: Piping
  shell: "virtualenv venv"
  args:
    chdir: "enos"
    creates: "enos/venv/bin/activate"
  when: inventory_hostname == openvpn_node


- name:
  copy:
    src: "{{ exec_dir }}/reservation.yaml"
    dest: /root/reservation.yaml
  when: inventory_hostname == openvpn_node
