---


- name: Get tars
  copy:
    src: "{{ exec_dir }}/current/{{ inventory_hostname }}.tar.gz"
    dest: "/root/{{ inventory_hostname }}.tar.gz"


- name: Extract directory
  unarchive:
    src: "/root/{{ inventory_hostname }}.tar.gz"
    dest: "/root/"
    remote_src: yes


- name: Copy shared key
  copy:
    src: "/root/{{ inventory_hostname }}/openvpn-shared-key.key"
    dest: /etc/openvpn/openvpn-shared-key.key
    remote_src: yes


- name: Copying delete route file
  copy:
    src: delete_route.sh
    dest: /root/delete_route.sh
    mode: "u=rwx,g=r,o=r"


- name: Using client.conf
  shell: "openvpn --daemon --config client.conf"
  args:
    chdir: "/root/{{ inventory_hostname }}/"


- name: Waiting a few seconds
  pause:
    seconds: 4


- name: Using client1.conf
  shell: "openvpn --daemon --config client1.conf"
  args:
    chdir: "/root/{{ inventory_hostname }}/"
