---

- name: Installing dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - openvpn
    - screen
    - bridge-utils
    - rsync


- name: Ensure group nobody exists
  group:
    name: nobody
    state: present


- name: Creates directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/openvpn
    - /etc/openvpn/keys


- name: Preparing master node when not adding node
  include: not_addition.yml
  when:
    - not addition
    - inventory_hostname == openvpn_node


- name: Preparing master node
  include: openvpn_node.yml
  when:
    - inventory_hostname == openvpn_node


- name: Other nodes
  include: others.yml
  when:
    - inventory_hostname != openvpn_node
    # - not addition


- name: Starting OpenVPN service
  shell: "openvpn --daemon ovpn-server --status /run/openvpn/server.status 10 --cd /etc/openvpn/server --config /etc/openvpn/{{ item }}"
  args:
    chdir: /etc/openvpn
  loop:
    - server.conf
    - server2.conf
  when:
    - inventory_hostname == openvpn_node
    - not addition


- name: Using client.conf
  shell: "openvpn --daemon --config client.conf"
  args:
    chdir: "/root/{{ inventory_hostname }}/"
  when: inventory_hostname in other_nodes


- name: Waiting a few seconds
  pause:
    seconds: 4


- name: Using client1.conf
  shell: "openvpn --daemon --config client1.conf"
  args:
    chdir: "/root/{{ inventory_hostname }}/"
  when: inventory_hostname in other_nodes


- name: Creating docker0 interface fix file
  template:
    src: create_docker0.sh.j2
    dest: /root/create_docker0.sh
    mode: "u=rwx,g=r,o=r"


- name: Executing docker0 interface fix file
  shell: "bash /root/create_docker0.sh"
