---

- name: Generating OpenVPN shared key
  shell: openvpn --genkey --secret /etc/openvpn/openvpn-shared-key.key
  args:
    creates: /etc/openvpn/openvpn-shared-key.key
  when: not addition

- name: Set ip forwarding on in /proc and in the sysctl file
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  when: not addition


- name: Iptables
  iptables:
    table: nat
    chain: POSTROUTING
    source: "{{ item }}"
    out_interface: eno1
    jump: MASQUERADE
  loop:
    - 11.8.0.0/24
    - 11.8.1.0/24
  when: not addition


- name: Copy easy-rsa
  synchronize:
    src: /usr/share/easy-rsa/
    dest: /etc/openvpn/easy-rsa/
  delegate_to: "{{ inventory_hostname }}"
  when: not addition


- name: Linking openssl conf
  file:
    src: /etc/openvpn/easy-rsa/openssl-1.0.0.cnf
    dest: /etc/openvpn/easy-rsa/openssl.cnf
    state: link
  when: not addition


- name: Preparing the keys directory
  shell: "touch /etc/openvpn/easy-rsa/index.txt; . ./vars; ./clean-all >/dev/null"
  args:
    chdir: "/etc/openvpn/easy-rsa/"
    creates: "/etc/openvpn/easy-rsa/index.txt"
  when: not addition


- name: Generating Diffie-Hellman parameters (takes some time)
  shell: ". ./vars; ./build-dh >/dev/null"
  args:
    chdir: "/etc/openvpn/easy-rsa/"
    creates: "/etc/openvpn/easy-rsa/keys/dh2048.pem"
  when: not addition


- name: Building CA
  shell: ". ./vars; ./pkitool --initca >/dev/null"
  args:
    chdir: "/etc/openvpn/easy-rsa/"
    creates: "/etc/openvpn/easy-rsa/keys/ca.key"
  when: not addition


- name: Generating server certificate and key
  shell: ". ./vars; ./pkitool --server server >/dev/null"
  args:
    chdir: "/etc/openvpn/easy-rsa/"
    creates: "/etc/openvpn/easy-rsa/keys/server.key"
  when: not addition


- name: Generating CRL file
  shell: ". ./vars; openvpn --genkey --secret keys/ta.key"
  args:
    chdir: "/etc/openvpn/easy-rsa/"
    creates: "/etc/openvpn/easy-rsa/keys/ta.key"
  when: not addition


- name: Creating directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /etc/openvpn/jail
    - /etc/openvpn/jail/tmp
    - /etc/openvpn/clientconf
    - /etc/openvpn/server
  when: not addition


- name: Copying keys to the server folder
  shell: "cp {{ item }} /etc/openvpn/server/"
  args:
    chdir: "/etc/openvpn/easy-rsa/keys"
  loop:
    - ca.crt
    - ta.key
    - server.key
    - dh2048.pem
    - server.crt
  when: not addition


- name: Creating server configuration
  template:
    src: server.conf.j2
    dest: /etc/openvpn/server.conf
  when: not addition


- name: Creating server2 configuration
  template:
    src: server2.conf.j2
    dest: /etc/openvpn/server2.conf
  when: not addition


- name: Getting openvpn key to put on other nodes
  fetch:
    src: /etc/openvpn/openvpn-shared-key.key
    dest: "{{ exec_dir }}/current/openvpn-shared-key.key"


- name: Generating clients certificates and keys
  shell: ". ./vars; ./pkitool {{ item }} >/dev/null"
  args:
    chdir: "/etc/openvpn/easy-rsa/"
    creates: "/etc/openvpn/easy-rsa/keys/{{ item }}.key"
  loop: "{{ other_nodes }}"


- name: Creating directories
  file:
    path: "/etc/openvpn/clientconf/{{ item }}"
    state: directory
  loop: "{{ other_nodes }}"


- name: Moving client keys
  shell: >
    cp easy-rsa/keys/ca.crt
    easy-rsa/keys/ta.key
    easy-rsa/keys/{{ item }}.crt
    easy-rsa/keys/{{ item }}.key
    clientconf/{{ item }}/
  args:
    chdir: "/etc/openvpn/"
    creates: "/etc/openvpn/clientconf/{{ item }}/ta.key"
  loop: "{{ other_nodes }}"


- name: Creating client configuration
  template:
    src: client.conf.j2
    dest: "/etc/openvpn/clientconf/{{ item }}/client.conf"
  loop: "{{ other_nodes }}"


- name: Creating client1 configuration
  template:
    src: client1.conf.j2
    dest: "/etc/openvpn/clientconf/{{ item }}/client1.conf"
  loop: "{{ other_nodes }}"


- name: Taring the client directories
  archive:
    path: "/etc/openvpn/clientconf/{{ item }}"
    dest: "/etc/openvpn/clientconf/{{ item }}.tar.gz"
    format: gz
  loop: "{{ other_nodes }}"


- name: Getting the archives to put on the nodes
  fetch:
    src: "/etc/openvpn/clientconf/{{ item }}.tar.gz"
    dest: "{{ exec_dir }}/current/"
    flat: yes
  loop: "{{ other_nodes }}"
